Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  # config.vm.provider "docker" do |d|
  #   d.image = "ubuntu"
  # end

  config.vm.synced_folder "../", "/vagrant_data"
  config.vm.provision :shell, path: "bootstrap.sh"
end
